### ISSUE TITLE
Error al crear New Job

### ISSUE THREAD

**Issue by Mikemex91** [abrahamcacoulides/prodfloor#10]
Si se selecciona la opcion de ninguno + alguna otra opcion al crear un trabajo M4000 se muestra una pantalla de error.

**Comment by abrahamcacoulides** [comment]
The issue was due to an error with the template that was being used by the FeaturesSelection form. This caused a validation error with the FormsWizard.

**Comment by abrahamcacoulides** [comment]
Template fixed. Issue solved on V0.2551
