### ISSUE TITLE
La aplicacion se queda trabada en el paso de beginning

### ISSUE THREAD

**Issue by Mikemex91** [abrahamcacoulides/prodfloor#13]
Al momento que se terminan todos los pasos de beginning y se oprime siguiente el programa no responde y no se puede proceder con las pruebas.

**Comment by abrahamcacoulides** [comment]
Problema con la apk, no desplegaba el pop up que valida que se termino el stage

**Comment by abrahamcacoulides** [comment]
El apk se actualizo
