### ISSUE TITLE
Se muestra la eficiencia del status en Negativo en un Element

### ISSUE THREAD

**Issue by emilioadrian** [abrahamcacoulides/prodfloor#51]
En el job 201708510 se mostraba una eficiencia negativa de -34% dutante las pruebas del Element

**Comment by abrahamcacoulides** [comment]
La funcion que determina la eficiencia reta el tiempo que se paso en paro por fin de turno, en este trabajo en particular el tiempo en paro por fin de turno era mayor que el tiempo que se le habia dedicado al controlador.
